// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oensgsrlykrokvgmvimy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbnNnc3JseWtyb2t2Z212aW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTE5MzksImV4cCI6MjA2ODgyNzkzOX0.-OomafrCpsM0m3AFdp6W0-nRXY4QzBDViR58nMK-ZV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});